apps/empresa/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    # Examples:
    # url(r'^$', 'karussa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^logout/$', 'apps.empresa.views.logOut', name='logout'),
    url(r'^perfil/$', 'apps.empresa.views.perfil_empresa', name='perfil'),

]

apps/instaladores/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url

urlpatterns = [
    # url(r'^$', 'apps.instaladores.views.test_karussa', name='test_karussa'),
    url(r'^descargar$', 'apps.instaladores.views.descargar_instalador', name='descargar_instalador'),
    url(r'^descargar_instalador$', 'apps.instaladores.views.post_descargar_instalador',
        name='post_descargar_instalador'),
]

apps/servicios/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'apps.servicios.views.home', name='home'),
    url(r'^servicios/configurar/$', 'apps.servicios.views.configurar', name='configurar'),
    url(r'^paquetes/configurar/$', 'apps.servicios.views.configurar_paquete', name='configurar_paquete'),
    url(r'^planes/$', 'apps.servicios.views.planes', name='planes'),
    #url(r'^iniciar-paquete/$', 'apps.servicios.views.iniciar_paquete', name='iniciar'),
    #url(r'^actualizar-hora/$', 'apps.servicios.views.actualizar_hora', name='actualizar_hora'),
    url(r'^contacto/$', 'apps.servicios.views.form_contacto', name='contacto'),
    url(r'^planes/finalizar/$', 'apps.servicios.views.finalizar_contacto', name='finalizar_contacto'),
]

apps/usuarios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    # Examples:
    # url(r'^$', 'karussa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^monitor$', 'apps.usuarios.views.vista_monitor', name='monitor'),
    url(r'^administrador$', 'apps.usuarios.views.vista_creador', name='creador'),
    url(r'^panel$', 'apps.usuarios.views.vista_godinez', name='godinez'),
    url(r'^administrador/configurar-usuarios$', 'apps.usuarios.views.configurar_usuarios', name='configurar_usuarios'),
    # url(r'^(?P<slug>[\w-]+)/login$', 'apps.usuarios.views.login_personalizado', name='login_personalizado'),
    # url(r'^login/$', 'apps.usuarios.views.login_normal', name='login_global'),
    url(r'^login/$', 'apps.usuarios.views.login_global', name='login'),
    url(r'^loginJava/$', 'apps.usuarios.views.login_java', name='login_java'),
    url(r'^eliminar$', 'apps.usuarios.views.eliminar_usuario', name='eliminar'),
    url(r'^karussa/$', 'apps.superuser.views.superuser', name='superuser'),
    url(r'^karussa/paquetes/crear$', 'apps.superuser.views.crear_paquete', name='crear_paquete'),
    url(r'^change_password$', 'apps.usuarios.views.change_password', name='change_password'),
    url(r'^password_change_done$', 'apps.usuarios.views.password_change_done', name='password_change_done'),

    # url(r'^ajax/agregar/monitor/$', 'apps.usuarios.views.ajax_agregar_monitor', name='ajax_agregar_monitor'),
]

karussa/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'karussa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^noSoy1admin/', include(admin.site.urls)),
    url(r'^', include('apps.empresa.urls', namespace='empresa_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^superuser/', include('apps.superuser.urls', namespace='superuser_app')),
    url(r'^', include('apps.servicios.urls', namespace='servicios_app')),
    url(r'^', include('apps.notificaciones.urls', namespace='notificaciones_app')),
    url(r'^', include('apps.demo.urls', namespace='demo_app')),
    url(r'^', include('apps.videos.urls', namespace='videos_app')),
    url(r'^', include('apps.instaladores.urls', namespace='instaladores_app')),

    #url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset',{'password_reset_form': EmailValidationOnForgotPassword , 'html_email_template_name':'mailing/mailing_renka_CAMBIA_TU_CONTRASENA.html', 'subject_template_name':'correos/asunto_password_reset.txt', 'from_email': 'RENKA <contacto@renka.com.mx>', }, name='reset_password_reset1'),
    #url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',name='password_reset_confirm'),
    #url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),


]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('', (
        r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

pruebas_notificaciones/swampdragon-TODOS/notifications/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from demo.views import Notifications

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', Notifications.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
)

pruebas_notificaciones/swampdragon-django-notifications-demo-master/swampdragon-django-notifications-demo-master/notifications/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#from demo.views import Notifications

admin.autodiscover()

urlpatterns = patterns('',
    #url(r'^$', Notifications.as_view(), name='home'),
    url(r'^$', 'demo.views.Notifications', name='home'),
    url(r'^home$', 'demo.views.Notifications_2', name='home_2'),
    url(r'^admin/', include(admin.site.urls)),
)

templates/base/base.html
{% load staticfiles %}
{% load static swampdragon_tags %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-STORE">
    <META HTTP-EQUIV="PRAGMA" CONTENT="NO-STORE">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>{% block title %}{% endblock %} - Karussa</title>

    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'base/css/remodal/remodal.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/remodal/remodal-default-theme.css' %}">

    <link rel="stylesheet" href="{% static 'base/css/base.css' %}"/>

    <style>
        body {
            /*background-image: url(
        {% static 'base/img/flowers.png' %} );*/
        }
    </style>

    {% block styles %}

    {% endblock %}

</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'servicios_app:home' %}">Karussa</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                {% if user.is_superuser %}
                    <li>
                        <a href="{% url 'superuser_app:superuser' %}">Superuser</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if user.isCreador %}
                        <li><a href="{% url 'usuarios_app:creador' %}">Administradores</a></li>
                    {% endif %}
                    {% if user.isMonitor %}
                        <li><a href="{% url 'usuarios_app:monitor' %}">Monitores</a></li>
                    {% endif %}
                    {% if user.isGodinez %}
                        <li><a href="{% url 'usuarios_app:godinez' %}">Usuarios</a></li>
                    {% endif %}
                {% endif %}
                <!--<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li class="divider"></li>s
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'servicios_app:contacto' %}">Contáctanos</a></li>
                    <li class="hidden"><a href="{% url 'servicios_app:configurar' %}">Configurar empresa</a></li>
                    <li><a href="{% url 'usuarios_app:login' %}">Iniciar sesión</a></li>
                {% else %}
                    <li>
                        <a href="{% url 'instaladores_app:descargar_instalador' %}">Descarga KarussApp</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            ¡Hola {{ user.get_short_name }}!
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            {% if user.isCreador %}
                                <li><a href="{% url 'usuarios_app:creador' %}">Vista Administrador</a></li>
                            {% endif %}
                            {% if user.isMonitor %}
                                <li><a href="{% url 'usuarios_app:monitor' %}">Vista Monitor</a></li>
                            {% endif %}
                            {% if user.isGodinez %}
                                <li><a href="{% url 'usuarios_app:godinez' %}">Vista Usuario</a></li>
                            {% endif %}
                            <li class="divider"></li>
                            <li><a href="{% url 'empresa_app:logout' %}">Salir</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div id="progress-page" class="progress progress-striped active" style="display: none;">
    <div class="progress-bar progress-bar-success" style="width: 100%"></div>
</div>

{% block content %}

{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="//cdn.jsdelivr.net/jquery.validation/1.14.0/jquery.validate.js"></script>
<script src="//cdn.jsdelivr.net/jquery.validation/1.14.0/additional-methods.min.js"></script>
<script src="{% static 'base/js/jquery.validate.español.js' %}"></script>
<script src="{% static 'base/js/jquery.blockUI.js' %}"></script>

<script>
    $.blockUI.defaults.message = '<i class="fa fa-refresh fa-spin fa-5x text-white"></i><p>Espere por favor, no recargue ni cierre la página</p>';
    $.blockUI.defaults.css = {
        padding: 0,
        margin: 0,
        width: '30%',
        top: '40%',
        left: '35%',
        textAlign: 'center',
        color: '#fff',
        border: 'none',
        backgroundColor: 'transparent',
        cursor: 'wait'
    };

    window.REMODAL_GLOBALS = {
        DEFAULTS: {
            hashTracking: false
        }
    };
</script>
<script src="{% static 'base/js/remodal/remodal.min.js' %}"></script>

{% if user.is_authenticated %}
    <!-- SwampDragon -->
    {% swampdragon_settings %}
    <script type="text/javascript" src="{% static 'swampdragon/js/dist/swampdragon.min.js' %}"></script>

    <!-- notifications -->
    <script type="text/javascript" src="{% static 'notificaciones/karussa_notificaciones.js' %}"></script>
{% endif %}
{% comment %}

    <script type="text/javascript" src="{% static 'notificaciones/notificaciones.js' %}"></script>
    <script type="text/javascript" src="{% static 'notificaciones/notifications.js' %}"></script>
    <script type="text/javascript" src="{% static 'notificaciones/karussa_notificaciones.js' %}"></script>
    <script type="text/javascript" src="{% static 'notificaciones/notificaciones.js' %}"></script>
{% endcomment %}

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });

    $(document).on('click', '.btn-progress', function () {
        $('#progress-page').fadeIn();
    });

</script>

{% block scripts %}

{% endblock %}


</body>
</html>