apps/usuarios/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url

urlpatterns = [
    # Examples:
    # url(r'^$', 'karussa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^monitor$', 'apps.usuarios.views.vista_monitor', name='monitor'),
    url(r'^administrador$', 'apps.usuarios.views.vista_creador', name='creador'),
    url(r'^panel$', 'apps.usuarios.views.vista_godinez', name='godinez'),
    url(r'^administrador/configurar-usuarios$', 'apps.usuarios.views.configurar_usuarios', name='configurar_usuarios'),
    # url(r'^(?P<slug>[\w-]+)/login$', 'apps.usuarios.views.login_personalizado', name='login_personalizado'),
    # url(r'^login/$', 'apps.usuarios.views.login_normal', name='login_global'),
    url(r'^login/$', 'apps.usuarios.views.login_global', name='login'),
    url(r'^loginJava/$', 'apps.usuarios.views.login_java', name='login_java'),
    url(r'^eliminar$', 'apps.usuarios.views.eliminar_usuario', name='eliminar'),
    url(r'^karussa/$', 'apps.superuser.views.superuser', name='superuser'),
    url(r'^karussa/paquetes/crear$', 'apps.superuser.views.crear_paquete', name='crear_paquete'),
    url(r'^change_password$', 'apps.usuarios.views.change_password', name='change_password'),
    url(r'^password_change_done$', 'apps.usuarios.views.password_change_done', name='password_change_done'),

    # url(r'^ajax/agregar/monitor/$', 'apps.usuarios.views.ajax_agregar_monitor', name='ajax_agregar_monitor'),
]

apps/videos/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url


urlpatterns = [
    # Examples:
    # url(r'^$', 'karussa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^(?P<slug>[\w-]+)/videos/(?P<llaveRandom>[\w-]+)$', 'apps.videos.views.abrirVideo', name='abrir_video'),
    url(r'^videos/stream/(?P<llaveRandom>[\w-]+)$', 'apps.videos.views.stream', name='stream'),
    url(r'^videos/streaming/(?P<nombre_archivo>[\w-]+)$', 'apps.videos.views.streaming', name='streaming'),
    url(r'^streaming/(?P<llave>[\w-]+)$', 'apps.videos.views.streaming_llave', name='streaming_llave'),

]

karussa/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'karussa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^noSoy1admin/', include(admin.site.urls)),
    url(r'^', include('apps.empresa.urls', namespace='empresa_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^superuser/', include('apps.superuser.urls', namespace='superuser_app')),
    url(r'^', include('apps.servicios.urls', namespace='servicios_app')),
    url(r'^', include('apps.notificaciones.urls', namespace='notificaciones_app')),
    url(r'^', include('apps.demo.urls', namespace='demo_app')),
    url(r'^', include('apps.videos.urls', namespace='videos_app')),
    url(r'^', include('apps.instaladores.urls', namespace='instaladores_app')),

    #url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset',{'password_reset_form': EmailValidationOnForgotPassword , 'html_email_template_name':'mailing/mailing_renka_CAMBIA_TU_CONTRASENA.html', 'subject_template_name':'correos/asunto_password_reset.txt', 'from_email': 'RENKA <contacto@renka.com.mx>', }, name='reset_password_reset1'),
    #url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',name='password_reset_confirm'),
    #url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),


]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('', (
        r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

pruebas_notificaciones/swampdragon-TODOS/notifications/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from demo.views import Notifications

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', Notifications.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
)

pruebas_notificaciones/swampdragon-django-notifications-demo-master/swampdragon-django-notifications-demo-master/notifications/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#from demo.views import Notifications

admin.autodiscover()

urlpatterns = patterns('',
    #url(r'^$', Notifications.as_view(), name='home'),
    url(r'^$', 'demo.views.Notifications', name='home'),
    url(r'^home$', 'demo.views.Notifications_2', name='home_2'),
    url(r'^admin/', include(admin.site.urls)),
)

apps/usuarios/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.conf import settings


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50,
                               required=True,
                               label='Email',
                               widget=forms.TextInput(attrs={
                                   'type': 'email',
                                   'class': 'form-control',
                                   'required': 'true',
                               }))
    password = forms.CharField(max_length=50,
                               required=True,
                               label='Contraseña',
                               widget=forms.TextInput(attrs={
                                   'type': 'password',
                                   'class': 'form-control',
                                   'required': 'true',
                               }))

    recordarme = forms.BooleanField(required=False,
                                    widget=forms.CheckboxInput())

    def clean(self):
        cleaned_data = self.cleaned_data
        recordarme = self.cleaned_data.get('recordarme')
        if not recordarme:
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
        else:
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
        return cleaned_data


class cambiarPasswordForm(forms.Form):
    pass

apps/usuarios/views.py
# -*- encoding: utf-8 -*-
from datetime import date, datetime

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http.response import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt

from apps.empresa.funciones import buscarEmpresaPorUsuario
from apps.empresa.models import Administrativos, Empresa
from apps.empresa.views import logOut
from apps.logger.funciones import logger
from apps.servicios.models import Paquete, Integrantes, VideosPaquete
from apps.usuarios.forms import LoginForm
from apps.usuarios.funciones import cargar_integrante, agregar_godinez, registrar_entrada, agregar_monitores
from apps.usuarios.models import Usuario, EmailOrUsernameModelBackend


@login_required
def vista_monitor(request):
    logger.info('Vista monitor')
    monitor = Integrantes.objects.filter(integrante=request.user.email, estado='Aceptado', nivel='monitor')
    error = ''
    if monitor.exists():
        debug = settings.DEBUG
        paquete = monitor[0].paquete
        usuario = Usuario.objects.get(id=request.user.id)
        if usuario.isMonitor:
            if request.method == 'POST':
                if "lista_correos_nuevos" in request.POST:
                    nuevos_godinez = []
                    lista_correos = request.POST.getlist('lista_correos_nuevos')
                    for correos in lista_correos:
                        for correo in correos.split(','):
                            nuevos_godinez.append(correo)
                    agregar_godinez(nuevos_godinez, paquete.empresa, usuario, paquete)
            try:
                integrantes = Integrantes.objects.filter(paquete=paquete, nivel="godinez")
                cantidad_godinez_libre = paquete.godinez - integrantes.count()
                # cantidad_godinez_libre = paquete.plan.cantidad - integrantes.count()
                lista_integrantes = []
                if integrantes.exists():
                    lista_integrantes = cargar_integrante(integrantes, lista_integrantes)
                return render(request, "usuarios/vista_monitor.html",
                              {'integrantes': lista_integrantes,
                               'nombre_empresa': paquete.empresa.nombre,
                               'usuarios_disponibles': cantidad_godinez_libre,
                               'DEBUG': debug})
            except Exception as e:
                error = e
                logger.exception(e)
    raise Http404(error)


@login_required
def vista_godinez(request):
    try:
        user = request.user
        integrantes = Integrantes.objects.filter(integrante=user.email, paquete__activo=True)
        if integrantes.exists():
            paquete = integrantes[0].paquete
            videos = VideosPaquete.objects.filter(paquete=paquete, fecha=date.today()).order_by("inicia")
            hora = datetime.today().time()
            return render(request, 'usuarios/vista_godinez.html', {
                'videos': videos,
                "hora": hora})
        return render(request, 'usuarios/fuera_de_servicio.html')
    except Exception as e:
        logger.exception(e)
        raise Http404(e.args)


def login_normal(request):
    lista_errores = []
    if request.user.is_authenticated():
        usuario = Usuario.objects.get(id=request.user.id)
        if usuario.is_superuser:
            return redirect(reverse('usuarios_app:superuser'))
        if usuario.isCreador:
            return redirect(reverse("usuarios_app:creador"))
        elif usuario.isMonitor:
            return redirect(reverse("usuarios_app:monitor"))
        elif usuario.isGodinez:
            return redirect(reverse("usuarios_app:godinez"))
        else:
            return render(request, 'usuarios/fuera_de_servicio.html')

    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        try:
            if login_form.is_valid():
                logger.info('Form válido')
                autentificar = EmailOrUsernameModelBackend()
                user, error = autentificar.authenticate(
                    username=login_form.cleaned_data['username'].lower().strip().replace(' ', '_'),
                    password=login_form.cleaned_data['password'])
                logger.info("user {0} error : {1}".format(user, error))
                if user is not None and error == 'ok':
                    user.backend = 'django.contrib.auth.backends.ModelBackend'
                    login(request, user)
                    if user.is_superuser:
                        return redirect(reverse('superuser_app:superuser'))
                    registrar_entrada(user)
                    logger.info('usuario existente', user)
                    slug = buscarEmpresaPorUsuario(user)
                    if slug == "":
                        logOut(request)
                    if user.isCreador:
                        return redirect(reverse("usuarios_app:creador"))
                    elif user.isMonitor:
                        return redirect(reverse("usuarios_app:godinez"))
                    elif user.isGodinez:
                        return redirect(reverse("usuarios_app:monitor"))
                    else:
                        return render(request, 'usuarios/fuera_de_servicio.html')
                else:
                    lista_errores.append(error)
                    logger.info('Usuario no existente', user)
                    logger.info('error : ', error)
        except Exception as e:
            lista_errores.append(e)
            logger.exception(e)
    return render(request, 'empresa/login.html',
                  {'login_form': login_form,
                   'errores': lista_errores})


def login_globalv2(request):
    url_redireccion = request.GET['next'] if 'next' in request.GET else '/'
    if request.user.is_authenticated():
        return redirect(url_redireccion)
    else:
        login_form = LoginForm()
        return render(request, 'empresa/login.html',
                      {'login_form': login_form})


def login_global(request):
    lista_errores = []
    url_redireccion = request.GET['next'] if 'next' in request.GET else "/"
    if request.user.is_authenticated():
        usuario = Usuario.objects.get(id=request.user.id)
        logger.info('usuario loggeado')
        logger.info(usuario.is_active)
        logger.info(usuario.id)
        if usuario.is_active:
            if usuario.is_superuser:
                return redirect(reverse('usuarios_app:superuser'))
            if usuario.isCreador:
                return redirect(reverse("usuarios_app:creador"))
            elif usuario.isMonitor:
                return redirect(reverse("usuarios_app:monitor"))
            elif usuario.isGodinez:
                if url_redireccion != "/":
                    return redirect(url_redireccion)
                return redirect(reverse("usuarios_app:godinez"))
            else:
                return render(request, 'usuarios/fuera_de_servicio.html')
        logger.info('se redireccionara al usuario para que cambie su password')
        return redirect(reverse("usuarios_app:change_password"))

    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        try:
            if login_form.is_valid():
                autentificar = EmailOrUsernameModelBackend()
                user, error = autentificar.authenticate(
                    username=login_form.cleaned_data['username'].lower().strip().replace(' ', '_'),
                    password=login_form.cleaned_data['password']
                )
                if user is not None and error == 'ok':
                    user.backend = 'django.contrib.auth.backends.ModelBackend'
                    login(request, user)
                    if user.is_active:
                        if user.is_superuser:
                            return redirect(reverse('superuser_app:superuser'))
                        registrar_entrada(user)
                        if user.isCreador:
                            return redirect(reverse("usuarios_app:creador"))
                        elif user.isMonitor:
                            return redirect(reverse("usuarios_app:monitor"))
                        elif user.isGodinez:
                            if url_redireccion != "/":
                                return redirect(url_redireccion)
                            return redirect(reverse("usuarios_app:godinez"))
                        else:
                            return render(request, 'usuarios/fuera_de_servicio.html')
                    else:
                        return redirect(reverse("usuarios_app:change_password"))
                else:
                    logger.info("error de logeo")
                    lista_errores.append(error)
                    logger.info(error)
        except Exception as e:
            lista_errores.append(e)
            logger.info("error del try")
            logger.info(e)
    return render(request, 'empresa/login.html',
                  {'login_form': login_form,
                   'errores': lista_errores})


# LOGIN CON JAVA
#   Solo se puede loguear por metodo POST
#   debe recibir un email y un password
#   si esta correcto, loggea al usuario
#   y retorna una notificacion al usuario con el nombre del canal, y demas informacion para configuracion
@csrf_exempt
def login_java(request):
    logger.info(request)
    lista_errores = []
    login_form = LoginForm()
    if request.method == 'GET':
        logger.info("Metodo GET en login_java ")
        return HttpResponse("ok")

    if request.method == "POST":
        logger.info("request.POST en login_java")
        logger.info(request.POST)

templates/usuarios/agregar_equipo.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}
    Agregar Equipo
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'base/css/bootstrap-tagsinput.css' %}"/>
    <style>
        .bootstrap-tagsinput {
            width: 100%;
            height: 200px;
        }
    </style>
{% endblock %}


{% block content %}
    <form action="" method="post" id="form-nuevos-usuarios">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ id }}">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-xs-12">
                            <h3>
                                Lista de monitores agregados
                            </h3>
                            {% if monitores %}
                                <table class="table table-striped table-hover ">
                                    <thead>
                                    <tr>
                                        <th>Eliminar</th>
                                        <th>Correo</th>
                                        <th>Estado</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for monitor in monitores %}
                                        <tr class="active">
                                            <td>
                                                <span class="btn btn-link btn-xs"
                                                      onclick="ajax_eliminar_monitor({{ id }}, '{{ monitor.integrante }}')"><i
                                                        class="fa fa-times text-danger"></i></span>
                                            </td>
                                            <td>{{ monitor.integrante }}</td>
                                            <td>{{ monitor.estado }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <p>No hay monitores agregados</p>
                            {% endif %}
                        </div>
                        <div class="col-xs-12">
                            {% if monitores_disponibles > 0 %}
                                <h3>Agregar nuevos monitores</h3>
                                <h5>
                                    Monitores disponibles para agregar: <span
                                        id="cantidad_correos_monitores">{{ monitores_disponibles }}</span>
                                </h5>

                                <div class="form-group">
                                    <label for="lista-correos-monitores">Lista de correos: (Separa cada correo con un
                                        espacio)</label>
                                    <input id="lista-correos-monitores" name="lista_correos_monitores"
                                           class="form-control input-xxlarge"
                                           type="text" data-role="tagsinput">
                                </div>
                            {% else %}
                                <h3>Gracias por asignar a los monitores</h3>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-xs-12">
                            <h3>
                                Lista de usuarios agregados
                            </h3>
                            {% if integrantes %}
                                <table class="table table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>Correo</th>
                                        <th>Ejercicio</th>
                                        <th>Hora</th>
                                        <th>Acciones</th>
                                        <th>Estado</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for integrante in integrantes %}
                                        <tr class="active">
                                            <td>

                                                <span class="btn btn-link btn-xs"
                                                      onclick="ajax_eliminar_usuario({{ id }}, {{ integrante.id }})"><i
                                                        class="fa fa-times text-danger"></i></span>

                                            </td>
                                            <td>{{ integrante.correo }}</td>
                                            <td>{{ integrante.ejercicio }}</td>
                                            <td>{{ integrante.hora }}</td>
                                            <td><span class="btn btn-warning btn-xs">Enviar aviso</span></td>
                                            <td>{{ integrante.activo }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <p>No hay usuarios agregados</p>
                            {% endif %}
                        </div>
                        <div class="col-xs-12">
                            {% if usuarios_disponibles %}
                                <h3>Agregar nuevos usuarios</h3>
                                <h5>
                                    Usuarios disponibles para agregar: <span
                                        id="cantidad_correos_usuarios">{{ usuarios_disponibles }}</span>
                                </h5>

                                <div class="form-group">
                                    <label for="lista-correos-usuarios">Lista de correos: (Separa cada correo con un
                                        espacio)</label>
                                    <input id="lista-correos-usuarios" name="lista_correos_usuarios"
                                           class="form-control input-xxlarge"
                                           type="text" data-role="tagsinput">
                                </div>
                            {% else %}
                                <h3>Gracias por agregar usuarios</h3>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 40px;">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-success pull-right" style="margin-top: 20px;">
                        Guardar cambios
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}


{% block scripts %}
    <script src="{% static 'base/js/bootstrap-tagsinput.min.js' %}"></script>
    <script>
        // Script para

        function ajax_eliminar_usuario(id_paquete, id_usuario) {
            $.ajax({
                url: "{% url 'usuarios_app:eliminar' %}",
                type: 'POST',
                data: {
                    'paquete': id_paquete,
                    'usuario_muerto': id_usuario
                },
                success: function () {
                    location.reload();
                }
            });
        }

        var $input_lista_correos_usuarios = $('input#lista-correos-usuarios');
        $input_lista_correos_usuarios.tagsinput({
            confirmKeys: [13, 32, 188, 44],
            trimValue: true,
            maxTags: {{ usuarios_disponibles }}
        });
        $input_lista_correos_usuarios.on('itemAdded', function (event) {
            var val_length = $input_lista_correos_usuarios.tagsinput('items').length;
            $('#cantidad_correos_usuarios').html(parseInt({{ usuarios_disponibles }}) - val_length);
        });
        $input_lista_correos_usuarios.on('itemRemoved', function (event) {
            var val_length = $input_lista_correos_usuarios.tagsinput('items').length;
            $('#cantidad_correos_usuarios').html(parseInt({{ usuarios_disponibles }}) - val_length);
        });

        $input_lista_correos_usuarios.on('itemAdded', function (event) {
            var tag = event.item;
            if (!isValidEmailAddress(tag)) {
                $input_lista_correos_usuarios.tagsinput('remove', tag);
            }
        });
        // End Script para usuarios

        // Script para monitores

        function ajax_eliminar_monitor(id_paquete, email_monitor) {
            $.ajax({
                url: "{% url 'usuarios_app:eliminar' %}",
                type: 'POST',
                data: {
                    'paquete': id_paquete,
                    'monitor_muerto': email_monitor
                },
                success: function () {
                    location.reload();
                }
            });
        }

        var $input_lista_correos_monitores = $('input#lista-correos-monitores');
        $input_lista_correos_monitores.tagsinput({
            confirmKeys: [13, 32, 188, 44],
            trimValue: true,
            maxTags: {{ usuarios_disponibles }}
        });
        $input_lista_correos_monitores.on('itemAdded', function (event) {
            var val_length = $input_lista_correos_monitores.tagsinput('items').length;
            $('#cantidad_correos_monitores').html(parseInt({{ monitores_disponibles }}) - val_length);
        });
        $input_lista_correos_monitores.on('itemRemoved', function (event) {
            var val_length = $input_lista_correos_monitores.tagsinput('items').length;
            $('#cantidad_correos_monitores').html(parseInt({{ monitores_disponibles }}) - val_length);
        });

        $input_lista_correos_monitores.on('itemAdded', function (event) {
            var tag = event.item;
            if (!isValidEmailAddress(tag)) {
                $input_lista_correos_monitores.tagsinput('remove', tag);
            }
        });
        // End Script para usuarios

        function isValidEmailAddress(emailAddress) {
            var pattern = new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);
            return pattern.test(emailAddress);
        }

        $('.bootstrap-tagsinput > input').keydown(function (event) {
            if (event.keyCode == 13 || event.which == 13) {
                event.preventDefault();
            }
            if ((event.keyCode || event.which) == 9) {
                $(this).focus();
                console.log('test');
            }
        });

    </script>

{% endblock %}

templates/usuarios/cambio_password_exitoso.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h3>Tu password ha sido actualizado correctamente :D</h3>
</body>
</html>

templates/usuarios/fuera_de_servicio.html
{% extends 'base/base.html' %}
{% block content %}
    <h1>Lo sentimos, fuera de servicio</h1>
{% endblock %}

templates/usuarios/vista_creador.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}
    Administrador
{% endblock %}

{% block content %}
    <div class="container">
        {% if paquetes %}
            <div class="row">
                <div class="col-xs-12">
                    <div class="alert alert-success text-center">
                        <h3 style="margin: 0;">¡Bienvenido, administrador de <b>{{ empresa.nombre|upper }}!</b></h3>
                        <input type="hidden" value="{{ slug }}" id="slg">
                    </div>
                    <h1>Paquetes de {{ empresa.nombre|upper }}: </h1>
                </div>
            </div>
            <div class="row">
                {% for paquete in paquetes %}
                    <div class="col-md-4">
                        <div class="well">
                            <p><strong>Inicio:</strong> {{ paquete.fecha_inicio|naturalday }}</p>
                            <p><strong>Duración:</strong> {{ paquete.duracion }} días</p>
                            <p><strong>Finaliza:</strong> {{ paquete.fecha_fin }} </p>
                            <p><strong>Usuarios:</strong> {{ paquete.cantidad_usuarios }}/{{ paquete.godinez }}</p>
                            <p><strong>Monitores:</strong> {{ paquete.cantidad_monitores }}/{{ paquete.monitores }}</p>
                            {% if paquete.activo %}
                                <p><strong>Estado:</strong> <i class="fa fa-play text-info"></i>&nbsp;&nbsp;Activo</p>
                            {% else %}
                                <p><strong>Estado:</strong> <i class="fa fa-pause text-muted"></i>&nbsp;&nbsp;Inactivo
                                </p>
                            {% endif %}
                            <form action="{% url "usuarios_app:configurar_usuarios" %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{ paquete.id }}"/>
                                <button class="btn btn-success btn-block" type="submit">Configurar usuarios</button>
                            </form>
                            <br>
                            <form action="#" method="post">
                                {% comment %}
                                    agregar la funcion que mande un correo ala chava para una extension o un nuevo
                                    paquete a esta empresa
                                {% endcomment %}
                                {% csrf_token %}
                                <button class="btn btn-success btn-block" type="submit">Solicitar Promocion</button>
                            </form>
                        </div>
                    </div>
                {% endfor %}

            </div>
        {% else %}
            <div class="jumbotron">
                <h2><i class="fa fa-clock-o text-muted"></i>&nbsp;&nbsp;Aún no tienes paquetes activos</h2>
                <p>Por favor, espera a que tu paquete sea activado, te notificaremos al correo: {{ user.email }}</p>
            </div>
        {% endif %}
    </div>

{% endblock %}

{% block scripts %}

    <script>

    </script>

{% endblock %}