apps/instaladores/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url

urlpatterns = [
    # url(r'^$', 'apps.instaladores.views.test_karussa', name='test_karussa'),
    url(r'^descargar$', 'apps.instaladores.views.descargar_instalador', name='descargar_instalador'),
    url(r'^descargar_instalador$', 'apps.instaladores.views.post_descargar_instalador',
        name='post_descargar_instalador'),
]

karussa/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'karussa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^noSoy1admin/', include(admin.site.urls)),
    url(r'^', include('apps.empresa.urls', namespace='empresa_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^superuser/', include('apps.superuser.urls', namespace='superuser_app')),
    url(r'^', include('apps.servicios.urls', namespace='servicios_app')),
    url(r'^', include('apps.notificaciones.urls', namespace='notificaciones_app')),
    url(r'^', include('apps.demo.urls', namespace='demo_app')),
    url(r'^', include('apps.videos.urls', namespace='videos_app')),
    url(r'^', include('apps.instaladores.urls', namespace='instaladores_app')),

    #url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset',{'password_reset_form': EmailValidationOnForgotPassword , 'html_email_template_name':'mailing/mailing_renka_CAMBIA_TU_CONTRASENA.html', 'subject_template_name':'correos/asunto_password_reset.txt', 'from_email': 'RENKA <contacto@renka.com.mx>', }, name='reset_password_reset1'),
    #url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',name='password_reset_confirm'),
    #url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),


]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('', (
        r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

pruebas_notificaciones/swampdragon-TODOS/notifications/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from demo.views import Notifications

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', Notifications.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
)

pruebas_notificaciones/swampdragon-django-notifications-demo-master/swampdragon-django-notifications-demo-master/notifications/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#from demo.views import Notifications

admin.autodiscover()

urlpatterns = patterns('',
    #url(r'^$', Notifications.as_view(), name='home'),
    url(r'^$', 'demo.views.Notifications', name='home'),
    url(r'^home$', 'demo.views.Notifications_2', name='home_2'),
    url(r'^admin/', include(admin.site.urls)),
)

apps/instaladores/models.py
import os

from django.db import models


# Create your models here.
def instaldor_path(instance, filename):
    return "intaladores/{file}".format(file=filename)


class Instalador(models.Model):
    archivo = models.FileField(max_length=1000, upload_to=instaldor_path)
    tipos = (("linux", "linux"), ("MAC", "MAC"), ("windows", "windows"))
    tipo = models.CharField(choices=tipos, max_length=30)
    titulo = models.CharField(max_length=30, default="")
    contador = 0

    def __str__(self):
        return self.titulo

    def __unicode__(self):
        return self.titulo

    @property
    def filename(self):
        return os.path.basename(self.archivo.name)

apps/instaladores/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http.response import Http404
from django.shortcuts import render

# Create your views here.

#### imports para jugar con archivos y descargarlos

from apps.instaladores.models import Instalador
from apps.logger.funciones import logger


@login_required
def descargar_instalador(request):
    return render(request, 'instaladores/descargar.html')


@login_required
def post_descargar_instalador(request):
    if "SO" in request.POST:
        try:
            archivo = Instalador.objects.get(tipo=request.POST["SO"]).archivo._get_file()
            response = HttpResponse(content_type='application/x-rar-compressed')
            response['Content-Disposition'] = 'attachment; filename="karussapp-{0}"'.format(request.POST['SO'] + '.rar')
            response.write(archivo.read())
            return response
        except Exception as e:
            logger.exception(e)
    raise Http404("no existe ese instalador")

templates/instaladores/descargar.html
{% extends 'base/base.html' %}
{% load staticfiles %}


{% block title %}
    Descargar KarussApp
{% endblock %}


{% block styles %}
    <style>
        img {
            margin: 40px auto;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row row-centered">
            <div class="col-xs-12 col-sm-8 col-md-6 col-centered text-center">
                <h1>Descarga KarussApp</h1>
                <p class="lead">Recibe las notificaciones en tu escritorio para poder continuar con tus sesiones de yoga
                    en Karussa.</p>
            </div>
        </div>
        <form action="{% url 'instaladores_app:post_descargar_instalador' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-4 text-center">
                    <h3>Windows</h3>
                    <img src="https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/128/OS_Windows_8.png"
                         alt="windows-icon" class="img-responsive">
                    <button type="submit" name="SO" value="windows" class="btn btn-primary btn-lg">Descargar para
                        Windows
                    </button>
                </div>
                <div class="col-sm-4 text-center">
                    <h3>Mac OS X</h3>
                    <img src="https://cdn0.iconfinder.com/data/icons/flat-round-system/512/mac_os_X-128.png"
                         alt="windows-icon" class="img-responsive">
                    <button type="submit" name="SO" value="MAC" class="btn btn-primary btn-lg">Descargar para Mac OS X
                    </button>
                </div>
                <div class="col-sm-4 text-center">
                    <h3>Ubuntu</h3>
                    <img src="https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/128/OS_Ubuntu.png"
                         alt="windows-icon" class="img-responsive">
                    <button type="submit" name="SO" value="linux" class="btn btn-primary btn-lg">Descargar para Ubuntu
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}